export const API_URL = `${process.env.API_ORIGIN}/api/weblarek`;
export const CDN_URL = `${process.env.API_ORIGIN}/content/weblarek`;

export const settings = {
  modalContentSelector: '.modal__content',
  modalCloseClass: 'modal__close',
  modalClass: 'modal',
  modalActiveClass: 'modal_active',
  basketListSelector: '.basket__list',
  basketPriceSelector: '.basket__price',
  basketButtonSelector: '.basket__button',
  basketItemIndexSelector: '.basket__item-index',
  basketItemTitleSelector: '.card__title',
  basketItemPriceSelector: '.card__price',
  basketItemDeleteSelector: '.basket__item-delete',
  cardCategorySelector: '.card__category',
  cardImageSelector: '.card__image',
  cardTitleSelector: '.card__title',
  cardPriceSelector: '.card__price',
  cardDescriptionSelector: '.card__text',
  cardInBasketButtonSelector: '.card__button',
  inBasketButtonText: 'В корзину',
  outFrombasketButtonText: 'Убрать',
  paymentButtonListSelector: '.order__buttons',
  addressInputName: 'address',
  emailInputName: 'email',
  phoneInputName: 'phone',
  submitButtonSelector: '.button',
  orderButtonSelector: '.order__button',
  paymentButtonClass: 'button_alt',
  paymentButtonClassActive: 'button_alt-active',
  basketCounterSelector: '.header__basket-counter',
  gallerySelector: '.gallery',
  basketSelector: '.header__basket',
  successTotalSelector: '.order-success__description',
  successCloseButtonSelector: '.order-success__close',
  cardCatalogTemplateSelector: '#card-catalog',
  cardPreviewTemplateSelector: '#card-preview',
  basketTemplateSelector: '#basket',
  cardBasketTemplateSelector: '#card-basket',
  orderTemplateSelector: '#order',
  userTemplateSelector: '#contacts',
  successModalTemplateSelector: '#success',
  modalContainerSelector: '#modal-container',
};

export enum Events {
  PRODUCT_LIST_CHANGED = 'product:listChanged',
  CARD_SELECT = 'card:select',
  BASKET_ADD = 'basket:add',
  BASKET_REMOVE = 'basket:remove',
  BASKET_COUNT_CHANGE = 'basket:countChange',
  BASKET_OPEN = 'basket:open',
  MODAL_CLOSE = 'modal:close',
  MODAL_OPEN = 'modal:open',
  MODAL_CLOSE_TRIGGER = 'modal:close:trigger',
  SHOW_ORDER_FORM = 'show:orderForm',
  PAYMENT_CHANGE = 'orderForm:paymentChange',
  ADDRESS_CHANGE = 'orderForm:addressChange',
  SHOW_USER_FORM = 'order:submit',
  EMAIL_CHANGE = 'contacts.email:change ',
  PHONE_CHANGE = 'contacts.phone:change',
  CONTACTS_ERRORS_CHANGE = 'userForm.errors:change',
  ORDER_ERRORS_CHANGE = 'orderForm.errors:change',
  USER_FORM_SUBMIT = 'contacts:submit',
  SHOW_SUCCESS_MODAL = 'show:successModal'
};

